version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      # one big pull request for minor bumps
      npm-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7
