name: binderhub-badge-commenter
description: Add a BinderHub link comment on PRs
author: Simon Li
inputs:
  githubToken:
    required: true
    description: GitHub token
  query:
    required: false
    description: Optional query string to pass to the launched server, for example `urlpath=lab`, will be used exactly as is (no escaping)
  binderUrl:
    required: true
    description: BinderHub base URL if not using mybinder.org
    default: https://mybinder.org
  environmentRepo:
    required: false
    description: If set then the current repository is used to supply the content for nbgitpuller, and the environment is built using `environmentRepo`. Must be in the form `<repo-type>/<repo>/<version>`, e.g. `gist/manics/c34db392c2bd2eb133c58c83c59358a1/HEAD`
  urlpath:
    required: false
    description: Optional URL path to pass to the launched server, for example `lab/tree/example.ipynb` or `rstudio`
  updateDescription:
    required: false
    description: If `true` then append the comment to the description instead of in a new comment
  persistentLink:
    required: false
    description: If `true` then the commit SHA will be used and the comment will be updated on subsequent runs, otherwise the branch name will be used
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: share-2
  color: blue
