name: 'binder-badge'
on:
  pull_request:
  # pull_request_target:

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
