name: test-and-update
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'

jobs:
  test-and-update:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm
      # Runs format, updates dist, runs tests
      - run: |
          npm install
          npm run all
          git diff
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: '[update-dist-bot] auto-format and update dist'
          commit_user_name: update-dist-bot
          commit_user_email: update-dist-bot@example.org
          commit_author: 'update-dist-bot <update-dist-bot@example.org>'
